artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/zamanwahid16/Datasets/raw/main/chicken_disease_data.zip
  local_data_file: artifacts/data_ingestion/data.zip
