artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/zamanwahid16/Datasets/raw/main/chicken_disease_data.zip
  local_data_file: artifacts/data_ingestion/data.zip


base_model:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/base_model.h5
  updated_base_model_path: artifacts/base_model/updated_base_model.h5


callbacks:
  root_dir: artifacts/callbacks
  tensorboard_logs_dir: artifacts/callbacks/tensorboard_logs
  checkpoint_model_path: artifacts/callbacks/checkpoints/model.h5


model_training:
  root_dir: artifacts/model_training
  trained_model_path: artifacts/model_training/model.h5
  training_data: artifacts/data_ingestion/chicken_disease_data

model_validation:
  root_dir: artifacts/model_validation
